# Generated by Django 5.2 on 2025-05-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_item', models.CharField(max_length=200)),
                ('has_been_claimed', models.BooleanField(default=False)),
            ],
        ),
    ]
